Repository Team-Sunshijo/Sunshijo-Frontend, pull requests merged in 2023-06, with the labels that each got.

#27 ➰ :: (#8) 로그인 페이지 퍼블리싱
  src/components/Login/index.tsx
Labels: 퍼블리싱

#28 ➰ :: (#10) 회원가입 페이지 퍼블리싱
  src/assets/Signup/index.ts
  src/assets/custom.d.ts
  src/assets/icons/SignPerson.svg
  src/assets/icons/index.ts
  src/components/Login/index.tsx
  src/components/Signup/index.tsx
Labels: 퍼블리싱

#30 ➰ :: (#14) header 퍼블리싱
  src/assets/icons/Alram.svg
  src/assets/icons/index.ts
  src/components/header/index.tsx
Labels: 퍼블리싱

#31 ➰ :: (#29) Router 구조 만들기
  src/App.tsx
  src/Router.tsx
  src/pages/LogoinPage.tsx
  src/pages/SignupPage.tsx
  src/pages/index.ts
  src/route/index.ts
  src/route/route-router.tsx
  src/router/MainRouter.jsx
Labels: 기능 추가

#35 ➰ :: (#25) 모달 추가
  src/App.tsx
  src/components/common/dropDown/index.tsx
  src/components/constant/performance.ts
  src/components/contance/index.ts
  src/components/performanceAssessment/index.tsx
  src/components/performanceAssessment/performanceModal.tsx
Labels: 기능 추가

#41 ➰ :: (#34) 로그인 & 회원가입 공통적인 요소 common으로 만들기
  src/components/Login/index.tsx
  src/components/Signup/index.tsx
  src/components/common/SignFrame/index.tsx
  src/components/common/SignFrame/style.ts
  src/pages/LogoinPage.tsx
  src/pages/SignupPage.tsx
Labels: 기능 추가

#45 ➰ :: (#37) 시간표 관리 페이지 퍼블리싱
  src/components/constant/performance.ts
  src/components/contance/index.ts
  src/components/models/List.ts
  src/components/timetableManagement/index.tsx
  src/components/timetableManagement/timetableBody.tsx
  src/components/timetableManagement/timetableHeader.tsx
  src/components/timetableManagement/timetableList.tsx
  src/constant/timetableManagement.ts
  src/pages/LogoinPage.tsx
  src/pages/PlanWritingDetailPage.tsx
  src/pages/SignupPage.tsx
  src/pages/TimetableManagementPage.tsx
Labels: 퍼블리싱

#47 ➰ :: (#46) 알림페이지 퍼블리싱
  src/components/Alarm/alarms.tsx
  src/components/Alarm/index.tsx
  src/pages/AlarmPage.tsx
Labels: 퍼블리싱

#50 ➰ :: (#48) 아이콘 파일 추가, 코드 수정
  src/assets/icons/Circle.svg
  src/assets/icons/Connection.svg
  src/components/Alarm/alarms.tsx
Labels: 기능 수정

#51 ➰ :: (#44) Calendar 추가
  package-lock.json
  package.json
  src/assets/icons/CalendarIcon.svg
  src/assets/icons/index.ts
  src/components/common/Calender/index.tsx
  yarn.lock
Labels: 기능 추가

#53 ➰ :: (#52) 알람 페이지 퍼블리싱 수정
  src/components/Alarm/alarms.tsx
  src/components/contance/index.ts
  yarn.lock
Labels: 기능 수정

#61 ➰ :: (#60) 시간표 관리 페이지에 모달 추가
  src/components/common/Calender/index.tsx
  src/components/common/modal/index.tsx
  src/components/performanceAssessment/index.tsx
  src/components/planWriting/planDetailReinforcement.tsx
  src/constant/performance.ts
Labels: 퍼블리싱

#62 ➰::(#59) Calender 수정
  src/components/common/Calender/index.tsx
Labels: 기능 수정

#65 ➰::(#64)헤더 로그아웃 버튼 모달 추가
  src/components/common/modal/index.tsx
  src/components/header/index.tsx
Labels: 퍼블리싱
